---
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    versioning-strategy: auto
    commit-message:
      prefix: "chore(cargo)"
    labels:
      - cargo
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: ci
    labels:
      - github-actions

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: "chore(nix)"
    labels:
      - nix
